"use client";

import React from 'react';
import { motion } from 'framer-motion';
import { FileText, Cpu, Eye, CheckCircle, Wifi, Globe, MessageSquare, Heart, Shield } from 'lucide-react';

export function Features() {
  const list = [
    {
      icon: <FileText className="w-5 h-5 text-indigo-500" />,
      title: "Interactive Study Summaries",
      desc: "Switch between 30s, 2m, bullet lists, detailed markdown, beginner terms, or expert formulas with one click."
    },
    {
      icon: <Cpu className="w-5 h-5 text-emerald-500" />,
      title: "Zoomable SVG Mind Maps",
      desc: "Explore visual logic dependencies. Collapse nodes, pan with mouse-drag, zoom in/out, and export directly as PNG."
    },
    {
      icon: <Eye className="w-5 h-5 text-amber-500" />,
      title: "Autogenerated Flashcards",
      desc: "Master key definitions using flip animations, difficulty ratings, bookmarks, and randomized testing modes."
    },
    {
      icon: <CheckCircle className="w-5 h-5 text-purple-500" />,
      title: "Gamified Quiz Assessments",
      desc: "Test recall with MCQs, true/false bounds, fill in the blanks, and code output challenges. Unlocks confetti on success."
    },
    {
      icon: <MessageSquare className="w-5 h-5 text-cyan-500" />,
      title: "ChatGPT Study Buddy",
      desc: "Chat with the video transcript. Code highlighting, suggested prompts, streaming tokens, and continuous followups."
    },
    {
      icon: <Globe className="w-5 h-5 text-pink-500" />,
      title: "Multi-Platform Copywriter",
      desc: "Turn lectures into LinkedIn summaries (professional, funny, startup) and formatted, character-counted Twitter threads."
    },
    {
      icon: <Wifi className="w-5 h-5 text-orange-500" />,
      title: "Offline PWA Native Mode",
      desc: "Install the app on iOS, Android, macOS or Windows. Access cached notes, history, and study timer offline."
    },
    {
      icon: <Shield className="w-5 h-5 text-red-500" />,
      title: "Code Snippet Sandbox UI",
      desc: "Extract programming syntax automatically. Highlighted code blocks with direct run simulations and download actions."
    }
  ];

  return (
    <section id="features" className="py-20 max-w-7xl mx-auto px-6 border-t border-border/40 relative">
      <div className="text-center space-y-3 mb-16">
        <h2 className="text-3xl sm:text-5xl font-bold tracking-tight">Built for Supercharged Learners</h2>
        <p className="text-muted-foreground text-sm sm:text-base max-w-xl mx-auto">
          We built everything you need to digest hours of lectures in minutes.
        </p>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
        {list.map((item, idx) => (
          <motion.div
            key={idx}
            initial={{ opacity: 0, y: 15 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-100px" }}
            transition={{ duration: 0.5, delay: idx * 0.05 }}
            whileHover={{ y: -4 }}
            className="p-6 bg-card border border-border rounded-2xl shadow-sm hover:shadow-md hover:border-border/80 transition-all flex flex-col justify-between"
          >
            <div className="space-y-4">
              <div className="w-10 h-10 rounded-xl bg-secondary flex items-center justify-center border border-border/40">
                {item.icon}
              </div>
              <div className="space-y-1.5">
                <h3 className="font-bold text-base text-foreground">{item.title}</h3>
                <p className="text-muted-foreground text-xs leading-relaxed">{item.desc}</p>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </section>
  );
}

export default Features;
