"use client";

import React, { useState } from 'react';
import { FileText, Copy, Share2, Sparkles, Award } from 'lucide-react';
import { toast } from 'sonner';

interface BlogPanelProps {
  blog: {
    title: string;
    content: string;
    seoScore: number;
    keywords: string[];
    readTime: string;
  };
}

export function BlogPanel({ blog }: BlogPanelProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const text = `${blog.title}\n\n${blog.content}`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    toast.success("Blog post copied to clipboard!");
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      
      {/* HEADER */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 border-b border-border/60 pb-3 select-none">
        <div className="space-y-1">
          <h3 className="font-bold text-sm text-foreground flex items-center gap-2">
            <FileText className="w-4.5 h-4.5 text-indigo-500" />
            AI Blog Article Generator
          </h3>
          <p className="text-[10px] text-muted-foreground">Autogenerated professional article based on lecture transcripts.</p>
        </div>

        <div className="flex items-center gap-2 select-none">
          <button
            onClick={handleCopy}
            className="px-3.5 py-2 rounded-xl bg-card border border-border/50 text-[11px] font-semibold text-foreground hover:bg-secondary/40 flex items-center gap-1.5 cursor-pointer"
          >
            <Copy className="w-3.5 h-3.5" />
            {copied ? 'Copied!' : 'Copy Article'}
          </button>
        </div>
      </div>

      {/* BODY SPLIT */}
      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6 items-start">
        
        {/* Blog Post Details (3 cols) */}
        <div className="lg:col-span-3 p-6 bg-card border border-border rounded-2xl space-y-4 prose dark:prose-invert">
          <h2 className="text-lg font-extrabold text-foreground border-b border-border/20 pb-2">
            {blog.title}
          </h2>
          <div className="flex items-center gap-3 text-[10px] text-muted-foreground font-semibold uppercase tracking-wider select-none">
            <span>By TubeMind AI Author</span>
            <span>•</span>
            <span>{blog.readTime}</span>
          </div>

          <div className="text-xs leading-relaxed text-foreground/90 space-y-4 pt-2">
            {blog.content.split('\n').map((line, idx) => {
              if (line.startsWith('### ')) {
                return <h3 key={idx} className="text-sm font-extrabold text-foreground pt-3">{line.slice(4)}</h3>;
              }
              if (line.startsWith('#### ')) {
                return <h4 key={idx} className="text-xs font-bold text-foreground pt-2">{line.slice(5)}</h4>;
              }
              if (line.startsWith('- ')) {
                return <li key={idx} className="list-disc pl-4">{line.slice(2)}</li>;
              }
              return <p key={idx} className="whitespace-pre-wrap">{line}</p>;
            })}
          </div>
        </div>

        {/* SEO Analytics Widget (1 col) */}
        <div className="p-4 bg-secondary/30 border border-border rounded-2xl space-y-5 select-none">
          {/* Radial score */}
          <div className="text-center space-y-2">
            <span className="text-[9px] font-bold text-muted-foreground uppercase">SEO Score</span>
            <div className="relative inline-flex items-center justify-center">
              {/* Radial Circle */}
              <svg className="w-20 h-20 transform -rotate-90">
                <circle cx="40" cy="40" r="34" stroke="var(--border)" strokeWidth="5" fill="transparent" />
                <circle cx="40" cy="40" r="34" stroke="var(--primary)" strokeWidth="5" fill="transparent"
                  strokeDasharray={`${2 * Math.PI * 34}`}
                  strokeDashoffset={`${2 * Math.PI * 34 * (1 - blog.seoScore / 100)}`}
                />
              </svg>
              <div className="absolute font-extrabold text-sm">{blog.seoScore}%</div>
            </div>
            <p className="text-[10px] text-muted-foreground font-medium">Optimized for search rankings</p>
          </div>

          {/* Keywords tags */}
          <div className="space-y-2">
            <span className="text-[9px] font-bold text-muted-foreground uppercase">Target Keywords</span>
            <div className="flex flex-wrap gap-1">
              {blog.keywords.map((k) => (
                <span
                  key={k}
                  className="px-2 py-0.5 rounded bg-card border border-border/50 text-[9px] text-foreground font-semibold"
                >
                  #{k}
                </span>
              ))}
            </div>
          </div>
        </div>

      </div>

    </div>
  );
}

export default BlogPanel;
